name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JavaFX Jmods
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-jmods.zip -OutFile javafx.zip
          Expand-Archive -Path javafx.zip -DestinationPath "${env:GITHUB_WORKSPACE}"


      - name: Build with Maven
        run: mvn clean package

      - name: Create custom JRE with jlink
        shell: cmd
        run: |
          set "JAVAFX_MODS=${{ github.workspace }}\javafx-jmods-21.0.7"
          if exist custom-jre rmdir /s /q custom-jre
          jlink --module-path "%JAVA_HOME%\jmods;%JAVAFX_MODS%" ^
            --add-modules java.base,java.logging,javafx.base,javafx.controls,javafx.fxml ^
            --output custom-jre ^
            --compress=2 ^
            --no-header-files ^
            --no-man-pages

      - name: Package app image with jpackage
        shell: cmd
        run: |
          jpackage ^
            --type app-image ^
            --input target ^
            --name GuessTheNumber ^
            --main-jar GuessTheNumber-1.0.2.jar ^
            --main-class co.dekoderpy.guessthenumber.MainApplication ^
            --runtime-image custom-jre


      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuessTheNumber
          path: GuessTheNumber/**