name: Build MSI Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-sdk.zip
          unzip javafx.zip -d ${{ github.workspace }}
        shell: bash

      - name: Build with Maven
        run: mvn clean package

      - name: Create custom JRE with jlink
        run: |
          $JAVAFX_MODS="${{ github.workspace }}/javafx-sdk-21.0.7/lib"
          jlink --module-path "%JAVA_HOME%/jmods;$JAVAFX_MODS" \ 
            --add-modules java.base,java.logging,javafx.base,javafx.controls,javafx.fxml \ 
            --output custom-jre \ 
            --compress=2 \ 
            --no-header-files \ 
            --no-man-pages

      - name: Package MSI with jpackage
        run: |
          jpackage \ 
            --type msi \ 
            --input target \ 
            --name GuessTheNumber \ 
            --main-jar GuessTheNumber-1.0.0.jar \ 
            --main-class co.dekoderpy.guessthenumber.MainApplication \ 
            --runtime-image custom-jre

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: GuessTheNumber-MSI
          path: GuessTheNumber-*.msi