name: Build EXE and macOS App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JavaFX JMODs
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            JMOD_URL="https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_osx-aarch64_bin-jmods.zip"
          else
            JMOD_URL="https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.7_windows-x64_bin-jmods.zip"
          fi

          curl -L -o javafx.zip "$JMOD_URL"
          unzip javafx.zip -d javafx
        shell: bash



      - name: Build with Maven
        run: mvn clean package

      - name: Create custom JRE (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          set "JAVAFX_MODS=%CD%\\javafx\\javafx-jmods-21.0.7"
          if exist custom-jre rmdir /s /q custom-jre
          jlink --module-path "%JAVA_HOME%\\jmods;%JAVAFX_MODS%" ^
            --add-modules java.base,java.logging,javafx.base,javafx.controls,javafx.fxml ^
            --output custom-jre ^
            --compress=2 ^
            --no-header-files ^
            --no-man-pages

      - name: Create custom JRE (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          JAVAFX_MODS="$PWD/javafx/javafx-jmods-21.0.7"
          rm -rf custom-jre
          jlink \
            --module-path "$JAVA_HOME/jmods:$JAVAFX_MODS" \
            --add-modules java.base,java.logging,javafx.base,javafx.controls,javafx.fxml \
            --output custom-jre \
            --compress=2 \
            --no-header-files \
            --no-man-pages



      - name: Package app (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          FOR /F %%F IN ('dir /b /a:-d target\\GuessTheNumber-*.jar') DO set MAIN_JAR=%%F
          jpackage ^
            --type app-image ^
            --input target ^
            --name GuessTheNumber ^
            --main-jar %MAIN_JAR% ^
            --main-class co.dekoderpy.guessthenumber.MainApplication ^
            --runtime-image custom-jre


      - name: Package app (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          MAIN_JAR=$(ls target/GuessTheNumber-*.jar | head -n 1)
          jpackage \
            --type app-image \
            --input target \
            --name GuessTheNumber \
            --main-jar "$(basename "$MAIN_JAR")" \
            --main-class co.dekoderpy.guessthenumber.MainApplication \
            --runtime-image custom-jre


      - name: Zip Windows App Folder
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path GuessTheNumber\* -DestinationPath GuessTheNumber-Windows.zip

      - name: Upload Windows ZIP as Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: GuessTheNumber-Windows
          path: GuessTheNumber-Windows.zip

      - name: Zip macOS .app Bundle
        if: matrix.os == 'macos-latest'
        run: |
          zip -r GuessTheNumber-macOS.zip GuessTheNumber.app


      - name: Upload macOS ZIP as Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: GuessTheNumber-macOS
          path: GuessTheNumber-macOS.zip



  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: GuessTheNumber-Windows
          path: windows/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: GuessTheNumber-macOS
          path: macos/

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            windows/**
            macos/**
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
